### ISSUE TITLE
Where to find Plugin Repository API description?

### ISSUE THREAD

**Issue by mskonovalov** [JetBrains/plugin-repository-rest-client#13]
I'd like to use methods are not provided by this plugin. How can I learn API?
Also do you support access tokens instead of password auth?

**Comment by zolotov** [comment]
As far as I know, there is no public version of API docs yet and there is no access tokens support either.

**Comment by mskonovalov** [comment]
Thanks for reply.
Maybe you can provide non-public docs?
I just want to read info about plugin in json format.
Unfortunately, I've tried different requests and jot only html responses.

**Comment by mikhailvink** [comment]
@mskonovalov Sure. Now there is no JSON API for plugin information, but there is an XML API IntelliJ IDEA relies on, I've provided an answer in a community forums topic today: https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000135184-Plugin-Repository-API

**Plugin List and Plugin Information API:**
You can use XML API which is a part of our IntelliJ-PluginsRepository protocol: https://plugins.jetbrains.com/plugins/list/?build=%PRODUCT_CODE%-%BUILD-NUMBER% (e.g. https://plugins.jetbrains.com/plugins/list/?build=IU-171.3780.107 for the latest IntelliJ IDEA Ultimate) to get a list of all compatible plugins for a product, and also https://plugins.jetbrains.com/plugins/list?pluginId=%PLUGIN_XMLID% (e.g. https://plugins.jetbrains.com/plugins/list?pluginId=IdeaVIM for IdeaVIM) to get information about the plugin.

>Also do you support access tokens instead of password auth?

We're planning to introduce it soon, but now it's not possible.

**Comment by mskonovalov** [comment]
Hi @mikhailvink, thank you for your reply.
I've taken XML API and parsed downloads count.
Thank you for your help.
