### ISSUE TITLE
PluginUpdateManager.getUpdateById deserialization error

### ISSUE THREAD

**Issue by jeffmaury** [JetBrains/plugin-repository-rest-client#48]
Marketplace is returning the list of compatible versions as a Map of products and versions. This is deserialized as a Map whose key is a `ProductEnum` but some requests returns **GATEWAY** as the enum id and it's not part of `ProductEnum` thus deserialization fails.
You can use this example: https://plugins.jetbrains.com/api/updates/63789

**Comment by AlexanderPrendota** [comment]
Hey, thanks! Should be fixed in 2.0.20 version
